// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://erbyxhjehrvpxvfycxwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyYnl4aGplaHJ2cHh2ZnljeHd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNDM1ODQsImV4cCI6MjA2MDgxOTU4NH0.yjH1gyZG0D-kxgQzZ2UNxeQh8l3v0RZxGTL5oizL5bI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);